# Generated by Django 5.2.8 on 2025-11-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0004_mcq'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=200),
        ),
    ]
