# Generated by Django 5.2.8 on 2025-11-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0006_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
