# Generated by Django 5.2.8 on 2025-11-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0007_remove_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
    ]
