# Generated by Django 5.2.8 on 2025-11-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0008_remove_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(null=True, unique=True),
        ),
    ]
